# Generated by Django 2.0.7 on 2018-07-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eltambo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gestore',
        ),
    ]
