# Generated by Django 2.0.7 on 2018-07-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltambo', '0002_delete_gestore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indirizzo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='id',
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='id_indirizzo',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodotto',
            name='id_prodotto',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utente',
            name='id_utente',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utente',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True),
        ),
    ]
