# Generated by Django 2.0.7 on 2018-07-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltambo', '0003_auto_20180714_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indirizzo',
            name='id_indirizzo',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='id_prodotto',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='id_utente',
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodotto',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
