# Generated by Django 2.0.7 on 2018-07-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltambo', '0004_auto_20180714_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='caratteristiche',
            field=models.CharField(choices=[('1', 'Nuovo'), ('2', 'Usato'), ('2', 'Nuovo-scontato'), ('2', 'Usato-scontato')], max_length=5),
        ),
    ]
