# Generated by Django 2.0.7 on 2018-07-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltambo', '0005_auto_20180716_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='caratteristiche',
            field=models.CharField(choices=[('1', 'Nuovo'), ('2', 'Usato'), ('3', 'Nuovo-scontato'), ('4', 'Usato-scontato')], max_length=5),
        ),
    ]
